name: Deploy Serverless Model

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Deploy SAM package
        run: ./deploy.sh
        env:
          AUTH0_SECRET_KEY: ${{ secrets.AUTH0_SECRET_KEY }}